name: 'Link artifacts in PR'
description: 'Link some or all artifacts in PR which has triggered workflow'
inputs:
  whitelist:
    description: 'artifact names to link in PR'
    required: false
    default: "[]"
  token:
    description: 'token is required to post comments'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
